# This is the docker-compose-yml file that must be able to start
# your group's backend.

# Remember to comment this file well!

# After you have Docker and Docker Compose installed,
# and this file is ready, you use this file and run it with:
# `docker-compose up --build`

version: "3"

services:
  # An example configuration of server A for groups' convenience.
  # server-a is based on the Docker image the groups produce and build themselves.
  server-a:
    container_name: server-a
    restart: always
    depends_on:
      - rabbitmq
      - mongodb
    build:
      dockerfile: Dockerfile
      context: ./backend/server-a
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mongodb:27017, rabbitmq:5672
      WAIT_AFTER_HOSTS: 5
    command: sh -c "/wait && node app.js"
    networks:
      - backend

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  # You can base this service on the rabbitmq:3-management Docker Hub image.
  # You need to expose the RabbitMQ port 5672 to other containers
  # in this  docker-compose.yml, and for the managent from a Web
  # server you needs to make the map the RabbitMQ container port
  # 15672 to host port you wish to use for this.
  # A set of needed Docker instructions like 'image:' are shown
  # below, groups should set their values. Groups are free to
  # CRUD the set of instructions as they see fit.
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - 15672:15672
    networks:
      - backend

  # much of the server-b service entry can be copied from server-a
  # service above. server-b directory Dockerfile has more
  # information.
  # A set of needed Docker instructions like 'image:' are shown
  # below, groups should set their values. Groups are free to
  # CRUD this set of instructions as they see fit.
  server-b:
    depends_on:
      - rabbitmq
      - server-a
    command: ["./utils/wait-for-it.sh", "rapid-runner-rabbit:5672", "--",  "npm", "start"]
    build:
      dockerfile: Dockerfile
      context: ./backend/server-b
    ports:
      - 9000:8000
    networks:
      - backend

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - server-a
      - server-b


  # Your group might want to use a database to store some data
  # You can use any database you wish, PostgreSQL, MySQL and
  # MongoDB have rather good Docker documentation and examples.
  # But some groups could find a way to do this without
  # databases (but I could not :-) )
  # database-service would go here.
  #database:
# Here we create a named network, that all the backend components
# must be added to for them to be able to communicate through
# exposed ports.
networks:
  backend:
    driver: bridge
# If you use databases for storing information, you can define
# their volumes here.
# Documentation: https://docs.docker.com/storage/volumes/
# Personally I like to look at the database's image's Dockerfile
# in the Docker Hub to see what directory it uses to store data.
# volumes:
